import Header from "@/components/header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";
import { Silkscreen } from "next/font/google";
import Footer from "@/components/footer";
import { Suspense } from "react";

const pixelFont = Silkscreen({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", pixelFont.variable)}>
      <body>
        <Header />
        {children}
        <Suspense fallback={<div>Loading...</div>}>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
